# Generated by Django 2.2.25 on 2022-01-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(blank=True, max_length=50, null=True)),
                ('EmployeeDepartment', models.CharField(blank=True, max_length=50, null=True)),
                ('EmployeeAge', models.IntegerField(blank=True, null=True)),
                ('EmployeePhone', models.CharField(blank=True, max_length=20, null=True)),
                ('EmployeeEmail', models.CharField(blank=True, max_length=40, null=True)),
                ('EmployeeCity', models.CharField(blank=True, max_length=40, null=True)),
                ('EmployeeSalary', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
