# Generated by Django 2.2.25 on 2022-01-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='EmployeeAge',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='EmployeeEmail',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='EmployeePhone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='EmployeeSalary',
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmployeeCity',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmployeeDepartment',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmployeeName',
            field=models.CharField(max_length=50),
        ),
    ]
