# Generated by Django 2.2.25 on 2022-01-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20220105_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='EmployeeId',
        ),
        migrations.AddField(
            model_name='employee',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
